# Generated by Django 4.2.2 on 2023-07-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_employee_options_employee_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='media/', verbose_name='Ссылка картинки'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='', max_length=50, verbose_name='Контактный телефон'),
        ),
    ]
