# Generated by Django 4.2.1 on 2023-07-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_employee_image_employee_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "verbose_name": "Сотрудник кафедры",
                "verbose_name_plural": "Сотрудники кафедры",
            },
        ),
        migrations.AlterField(
            model_name="employee",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="media/", verbose_name="Ссылка картинки"
            ),
        ),
    ]
