# Generated by Django 4.2.2 on 2023-06-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Название')),
                ('anons', models.CharField(default='', max_length=250, verbose_name='Анонс')),
                ('full_text', models.TextField(default='', max_length=25000, verbose_name='Статья')),
                ('date', models.DateTimeField(default='', verbose_name='Дата публикации')),
            ],
        ),
    ]
