# Generated by Django 4.2.2 on 2023-06-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_artic_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='artic',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='media/', verbose_name='Ссылка картинки'),
        ),
    ]
