# Generated by Django 4.2.1 on 2023-07-08 05:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_rename_image_artic_image1_artic_image2_artic_image3_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artic",
            name="image4",
        ),
    ]
